version: '3.8'

services:
  newpoint:
    build:
      context: .
      dockerfile: NewPoint/Dockerfile
    ports:
      - "5136:5136"
    networks:
      - grpc-network
  
  newpoint-userapi:
    build:
      context: .
      dockerfile: NewPoint.UserAPI/Dockerfile
    ports:
      - "5137:5137"
    volumes:
      - ./NewPoint.UserAPI:/src/NewPoint.UserAPI
    networks:
      - grpc-network
  
  newpoint-verificationapi:
    build:
      context: .
      dockerfile: NewPoint.VerificationAPI/Dockerfile
    ports:
      - "5138:5138"
    volumes:
      - ./NewPoint.VerificationAPI:/src/NewPoint.VerificationAPI
    networks:
      - grpc-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - newpoint
      - newpoint-userapi
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
